[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
uvloop = "^0.19.0"
tgcrypto = "^1.2.5"
black = "^24.4.2"
pyrogram = "^2.0.106"
apscheduler = "^3.10.4"
loguru = "^0.7.2"
pydantic = "^2.7.1"
pyyaml = "^6.0.1"
types-pyyaml = "^6.0.12.20240311"
ruff = "^0.4.5"
